### ISSUE TITLE
issue with signal_handler

### ISSUE THREAD

**Issue by snikulov** [retf/Boost.Application#47]
Currently we have local object std|boost thread which is created in signal_handler here

https://github.com/retf/Boost.Application/blob/master/include/boost/application/signal_binder.hpp#L205

When std::thread is used it produce crash.
When boost::thread used it works, because of boost call detach() on joinable threads. See here - http://www.boost.org/doc/libs/1_59_0/doc/html/thread/thread_management.html#thread.thread_management.thread.destructor 

If I build example with BOOST_THREAD_PROVIDES_THREAD_DESTRUCTOR_CALLS_TERMINATE_IF_JOINABLE it also crashed.

Should be fixed either using detach() for this thread, or not produce thread at all 
``` spawn(ec, signal_number); ```
,
or keep pointer or reference to this thread anywhere.

Minimal example to demonstrate issue here https://github.com/snikulov/boost.app.minimal

**Comment by donbcd** [comment]
With regards to exception-safety, wouldn't it be best anyway to use a scoped thread, just with a little helper class that does the required (or not required) cleanup on destruction?

**Comment by snikulov** [comment]
@donbcd do you mean that it was by design? 
According to spec:

```
30.3.1.3 thread destructor [thread.thread.destr] ~thread();

If joinable(), calls std::terminate(). Otherwise, has no effects.
```
so it definitely should not be local or explicitly detachable.

**Comment by donbcd** [comment]
@snikulov What I mean is that, because of 30.3.1.3, there should never be a thread-object lying around on the stack. So there are a few possibilites:
- have not a thread at all (didn't look at it if the thread for spawn is really needed)
- detach() the thread immediately (bad: what happens if an exception occurs between thread creation and detach()? correct: std::terminate())
- have a wrapper class holding the thread-object and on destruction (e.g. because of an exception) checks if the thread is joinable(), and if so, either detaches or joins

The latter seems to be the safest solution for me. Quick untested pseudocode:

	class scoped_thread_joiner
	{
		public:
			template<typename Fun, typename ... Args>
			scoped_thread_joiner(Fun f, Args ... args) 
				: t_(std::thread(f, args...)) {}
			
			~scoped_thread_joiner()
			{
				if(t_.joinable()) t_.join(); // or detach
			}
		
		private:
			std::thread t_;
	};
